/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graficarfunciones.vista;

import com.singularsys.jep.JepException;
import graficarfunciones.funcion;
import graficarfunciones.metodo;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.math.plot.Plot2DPanel;
/**
 * @author OMAR LEZAMAP
 * Recuperado de: https://youtu.be/NIpjixNP1Qc por Javier Sarango
 */
public class graficarFun extends javax.swing.JFrame {

    Plot2DPanel grafica = new Plot2DPanel();

    /**
     * Creates new form graficarFun
     */
    public graficarFun() {
        initComponents();
        grafica.setBounds(0, 10, 420, 340);
        
        PanelGrafico.add(grafica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        x0 = new javax.swing.JTextField();
        x1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        txtMaxEntero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        PanelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gráfica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("f(x) =");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 40, 41, 25);
        jPanel2.add(txtFuncion);
        txtFuncion.setBounds(70, 40, 230, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parámetros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("X1 =");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 80, 30, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("X2 =");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 30, 30, 30);
        jPanel3.add(x0);
        x0.setBounds(60, 30, 70, 30);
        jPanel3.add(x1);
        x1.setBounds(60, 80, 70, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 90, 190, 160);

        jLabel4.setText("Error:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 120, 50, 30);

        jLabel5.setText("Máximo Entero:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(210, 170, 90, 30);

        txtError.setEditable(false);
        txtError.setText("1e-6");
        txtError.setEnabled(false);
        txtError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErrorActionPerformed(evt);
            }
        });
        jPanel2.add(txtError);
        txtError.setBounds(300, 120, 140, 30);

        txtMaxEntero.setEditable(false);
        txtMaxEntero.setText("100");
        txtMaxEntero.setEnabled(false);
        jPanel2.add(txtMaxEntero);
        txtMaxEntero.setBounds(300, 170, 140, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Raíz:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 260, 40, 30);

        txtRaiz.setEditable(false);
        txtRaiz.setEnabled(false);
        jPanel2.add(txtRaiz);
        txtRaiz.setBounds(70, 260, 350, 30);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcular);
        btnCalcular.setBounds(180, 310, 90, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 460, 400);

        PanelGrafico.setLayout(null);
        jPanel1.add(PanelGrafico);
        PanelGrafico.setBounds(470, 20, 420, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 420);

        setSize(new java.awt.Dimension(915, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        try {
            String def = txtFuncion.getText().trim();
            double lx0 = Double.parseDouble(x0.getText());
            double lx1 = Double.parseDouble(x1.getText());
            double le = Double.parseDouble(txtError.getText());
            Integer ln = Integer.valueOf(txtMaxEntero.getText());
            
            funcion ff = new funcion(def);
            metodo s = new metodo();
            double r = s.raiz(ff, lx0, lx1, ln, le);
            txtRaiz.setText("" + r);
            
            double[] x = new double[200];
            double[] y = new double[200];
            double xi = lx0 - 10;
            for (int i = 0; i < 200; i++) {
                x[i] = xi + i * 0.1;
                y[i] = ff.evaluar(x[i]);
            }
            grafica.addLegend("South");
            grafica.removeAllPlots();
            grafica.addLinePlot(def, x, y);
        } catch (JepException ex) {
            Logger.getLogger(graficarFun.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(graficarFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(graficarFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(graficarFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(graficarFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new graficarFun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGrafico;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtMaxEntero;
    private javax.swing.JTextField txtRaiz;
    private javax.swing.JTextField x0;
    private javax.swing.JTextField x1;
    // End of variables declaration//GEN-END:variables
}
